[workspace]
members = [
    "aoc2021",
    "aoc2022"
]

[workspace.package]
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2021"

[workspace.dependencies]
criterion = "0.4.0" # dev
csv = "1.1"
rayon = "1.5"
rstest = "0.16.0" # dev