[package]
name = "adventofcode2021"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
rayon = "1.5"

[dev-dependencies]
criterion = "0.3"
rstest = "0.12"

[[bench]]
name = "advent_benchmark"
harness = false

[lib]
bench = false