pub const TEST_DATA_0_1: [&'static str; 7] = [
    "start-A",
    "start-b",
    "A-c",
    "A-b",
    "b-d",
    "A-end",
    "b-end",
];

pub const TEST_DATA_0_2: [&'static str; 10] = [
    "dc-end",
    "HN-start",
    "start-kj",
    "dc-start",
    "dc-HN",
    "LN-dc",
    "HN-end",
    "kj-sa",
    "kj-HN",
    "kj-dc",
];

pub const TEST_DATA_1: [&'static str; 18] = [
    "fs-end",
    "he-DX",
    "fs-he",
    "start-DX",
    "pj-DX",
    "end-zg",
    "zg-sl",
    "zg-pj",
    "pj-he",
    "RW-he",
    "fs-DX",
    "pj-RW",
    "zg-RW",
    "start-pj",
    "he-WI",
    "zg-he",
    "pj-fs",
    "start-RW",
];

pub const TEST_DATA_2: [&'static str; 25] = [
    "start-co",
    "ip-WE",
    "end-WE",
    "le-ls",
    "wt-zi",
    "end-sz",
    "wt-RI",
    "wt-sz",
    "zi-start",
    "wt-ip",
    "YT-sz",
    "RI-start",
    "le-end",
    "ip-sz",
    "WE-sz",
    "le-WE",
    "le-wt",
    "zi-ip",
    "RI-zi",
    "co-zi",
    "co-le",
    "WB-zi",
    "wt-WE",
    "co-RI",
    "RI-ip",
];